# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: false

# index page config
index:
  # hero section
  hero:
    #
    title: <a href="/about">ì „í˜¸ê· </a>ì˜ ê°œë°œ/ë””ìì¸ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤. # ë©”ì¸ íƒ€ì´í‹€ì…ë‹ˆë‹¤.
    #
    subtitle: Hogyun Jeon's Development/Designing Blog #ì„œë¸Œ íƒ€ì´í‹€ì…ë‹ˆë‹¤.
    #
    nickname: hoqn # yournickname
    #
    nickname_link: /about
    #
    social:
      GitHub: https://github.com/hoqn
      Instagram: https://instagram.com/exhogyun
      # LinkedIn: https://linkedin.com/

  profile:
    img: /theme-img/profile-img.png
    h1: ì „í˜¸ê· 
    h2: Hogyun Jeon
    h3: ë‹¤ì‹œ ì‹œì‘í•˜ëŠ” ê°œë°œì

# navigation config
nav:
  # logo
  #logo: /theme-img/github-mark-dark.png
  # the title displays in the upper left corner which won't change
  logo: /theme-img/logo.svg
  title: "hoqn_dev" #"ì „í˜¸ê· ì˜ ë¸”ë¡œê·¸" #"ì „í˜¸ê· ì˜ ë¸”ë¡œê·¸" # Hogyunic Dev.
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    ì†Œê°œ: /about
    #í”„ë¡œì íŠ¸: /projects
    ë¸”ë¡œê·¸: /archives
    í¬íŠ¸í´ë¦¬ì˜¤: https://portfolio.hoqn.net
  social:
    # these will be automatically be an icon
    github: https://github.com/hoqn
  # whether to show the dark mode swtich
  show_dark_mode_switch: true
  # whether to show the search button in the upper right corner
  show_search_item: true
  # nav items style: [Colored or Colorless]
  colored_nav_items: false

# footer
footer:
  # footer items
  links:
    ë¸”ë¡œê·¸:
      ì†Œê°œ: /about
      ë¸”ë¡œê·¸: /archives
      í”„ë¡œì íŠ¸: /projects
      RSS: /rss
    ë‚˜:
      GitHub: https://github.com/hoqn
      Email: mailto:akzm9999@gmail.com
  # copyright
  infotext: <strong>ì „í˜¸ê· </strong>ì´ ğŸ’™ë¥¼ ë‹´ì•„ ë§Œë“¤ì—ˆìŠµë‹ˆë‹¤.<br>
    í…Œë§ˆëŠ” ë”°ë¡œ ê³µìœ í•˜ì§„ ì•ŠìŠµë‹ˆë‹¤.<br>
    <br>
    Copyright Â© JEON Hogyun 2020-2021.<br>
    All Rights Reserved.

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0
# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!
